---
 - 
   hosts: all
   become: yes
   #remote_user: root
   vars:
     linux_amd64_query: 'assets[?ends_with(name, "linux_amd64")].browser_download_url'
   pre_tasks:
     - name: 'Get apt list'
       raw: sudo apt-get update && sudo apt-get -y install python
   roles:
     - { role: "githubixx.kubectl", tags: ["kubectl"] } 
     - { role: "nickjj.user", tags: ["user"] } 
     - { role: "nickjj.docker", tags: ["docker"] } 

   tasks:
#   - name: Install Google skaffold
#     get_url:
#       url: https://github.com/GoogleContainerTools/skaffold/releases/download/v0.20.0/skaffold-linux-amd64
#       dest: /usr/local/bin/skaffold
#       mode: 555

   - name: Install packages - pass1
     apt:
       name: "{{packages}}"
     vars:
       packages:
         - curl 
         - python-pip
         - ruby
         - wget
         - jq
         - bash-completion
         - apt-transport-https
         - sudo
         - gnupg2
         - git
         - tmux

   - name: Get latest url for linux-amd64 release for aws-iam-authenticator
     uri:
       url: https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest
       return_content: true
       body_format: json
     register: aia_response

#   - name: The json_response
#     debug:
#       var: json_response.json
#
#          - name: Running a simple filter
#            debug:
#              var: " {{ json_response.json |to_json | from_json | json_query(\"assets[?ends_with(name,'linux_amd64')].browser_download_url | [0]\") }} "

   - name: Download and install aws-iam-authenticator
     get_url:
       url: " {{ aia_response.json | to_json | from_json| json_query(\"assets[?ends_with(name,'linux_amd64')].browser_download_url | [0]\") }}"
       mode: 555
       dest: /usr/local/bin/aws-iam-authenticator

   - name: Get latest url for linux-amd64 release for skaffold
     uri:
       url: https://api.github.com/repos/GoogleContainerTools/skaffold/releases/latest
       return_content: true
       body_format: json
     register: skaffold_response
 

   - name: Download and install skaffold
     get_url:
       url: "{{ skaffold_response.json | to_json | from_json| json_query(\"assets[?ends_with(name,'linux-amd64')].browser_download_url | [0]\") }}"
       mode: 555
       dest: /usr/local/bin/skaffold
     debugger: on_failed

   - name: Install helm
     script: scripts/install-helm.sh --version v2.11.0

   - name: Install awscli
     pip: 
       name: awscli

# - hosts: localhost
#   become: yes
#
#   vars:
#     minio_server_datadirs: ["/data/minio"]
#     minio_access_key: "minioaccess"
#     minio_secret_key: "miniosecret"
#   roles:
#     - atosatto.minio

   - name: Place custom tmux config
     copy:
       src: scripts/tmux.conf
       dest: /etc/tmux.conf
       owner: root
       group: root
       mode: 0644

   - name: Enable IP forwarding
     sysctl:
       name: net.ipv4.ip_forward
       value: 1
       sysctl_set: yes
       state: present
       reload: yes

   - name: Disable all ipv6
     sysctl:
       name: net.ipv6.conf.all.disable_ipv6
       value: 1
       sysctl_set: yes
       state: present
       reload: yes
